/* Bilingual content for Kauan Felipe portfolio. window.PORTFOLIO = { pt, en } */
(function () {
  const shared = {
    name: "Kauan Felipe",
    fullName: "Kauan Felipe Avelino de Lima",
    email: "kauan_falima@hotmail.com",
    phone: "+55 43 99979-6321",
    github: "https://github.com/kauanfelipe96",
    linkedin: "https://www.linkedin.com/in/kauanfelipe96",
    cv: "assets/Kauan-Felipe-CV.pdf",
    initials: "KF",
  };

  const skills = {
    backend: [".NET 9 (C#)", "ASP.NET", "APIs RESTful", "EF Core", "Dapper"],
    frontend: ["React", "Vite", "Tailwind CSS", "MVC (Razor)"],
    data: ["SQL Server", "Stored Procedures", "Triggers"],
    devops: ["GitHub Actions", "Docker", "Portainer", "CI/CD"],
    practices: ["DDD", "SOLID", "Clean Code", "Scrum"],
  };

  const pt = {
    lang: "pt",
    ...shared,
    role: "Desenvolvedor Full Stack",
    location: "Cornélio Procópio, Brasil",
    available: "Disponível para novos projetos",
    nav: { work: "Experiência", skills: "Stack", projects: "Projetos", education: "Formação", contact: "Contato" },
    hero: {
      eyebrow: "Desenvolvedor Full Stack · .NET & React",
      headline: "Construo sistemas confiáveis que sustentam negócios.",
      sub: "Back-end em .NET, front-end em React e DevOps de ponta a ponta — do banco de dados ao deploy. Foco em código limpo, performance e impacto mensurável.",
      ctaPrimary: "Ver experiência",
      ctaSecondary: "Baixar CV",
      stats: [
        { value: "4+", label: "anos de experiência" },
        { value: "99,9%", label: "uptime em produção" },
        { value: "1.000+", label: "transações/mês integradas" },
      ],
      terminalLines: [
        "$ whoami",
        "kauan_felipe — full stack developer",
        "$ stack --primary",
        ".NET 9 · C# · React · SQL Server · Docker",
        "$ status",
        "● disponível para novos desafios",
      ],
    },
    workTitle: "Experiência",
    workKicker: "Onde estou criando impacto",
    work: [
      {
        company: "Aquativa Golf Resort",
        role: "Desenvolvedor Full Stack",
        place: "Cornélio Procópio, BR",
        period: "Jan 2025 — Presente",
        current: true,
        bullets: [
          "Modernizei APIs RESTful legadas em .NET, aumentando o tempo de resposta em 35% e reduzindo erros em 25%.",
          "Implementei fluxos de pagamento ponta a ponta com integração bancária (Bradesco), processando 1.000+ transações/mês com 99,5% de sucesso.",
          "Integrei o ERP TOTVS automatizando sincronização de dados e reduzindo entrada manual em 80%.",
          "Estabeleci CI/CD com GitHub Actions e Docker, cortando o deploy de 2h para 15min.",
        ],
        tags: [".NET", "React", "SQL Server", "Docker", "CI/CD"],
      },
      {
        company: "Bono Energia",
        role: "Analista de Sistemas (Pleno)",
        place: "Londrina, BR",
        period: "Jul 2023 — Dez 2023",
        bullets: [
          "Desenvolvi APIs RESTful em .NET Core integrando 5+ sistemas internos e externos.",
          "Implementei políticas de segurança atingindo 100% de conformidade com padrões de SI.",
          "Otimizei 20+ stored procedures, deixando consultas 40% mais rápidas.",
        ],
        tags: [".NET Core", "WebService", "SQL", "Scrum"],
      },
      {
        company: "Dribion Software",
        role: "Suporte Técnico",
        place: "Cornélio Procópio, BR",
        period: "Jan 2021 — Abr 2022",
        bullets: [
          "Resolvi 200+ problemas técnicos/mês com 95% de resolução no primeiro contato.",
          "Treinei 50+ clientes e 10+ funcionários, reduzindo tickets de suporte em 30%.",
          "Gerenciei emissão fiscal (NFe, NFC, MDFe, CTe) com 100% de conformidade.",
        ],
        tags: ["SQL Server", "Suporte", "QA", "Fiscal"],
      },
    ],
    skillsTitle: "Stack & Tecnologias",
    skillsKicker: "As ferramentas que uso todos os dias",
    skillGroups: [
      { label: "Back-end", items: skills.backend },
      { label: "Front-end", items: skills.frontend },
      { label: "Bancos de Dados", items: skills.data },
      { label: "DevOps", items: skills.devops },
      { label: "Práticas", items: skills.practices },
    ],
    projectsTitle: "Projetos em Destaque",
    projectsKicker: "Trabalhos selecionados",
    projectsNote: "// substitua estes cards pelos seus projetos reais — nome, descrição, link e print",
    projects: [
      { name: "Projeto 01", desc: "Descreva aqui o problema que resolveu e o resultado obtido.", tags: ["React", "API"], slot: "print do projeto 01" },
      { name: "Projeto 02", desc: "Descreva aqui o problema que resolveu e o resultado obtido.", tags: [".NET", "SQL"], slot: "print do projeto 02" },
      { name: "Projeto 03", desc: "Descreva aqui o problema que resolveu e o resultado obtido.", tags: ["Docker", "CI/CD"], slot: "print do projeto 03" },
    ],
    educationTitle: "Formação",
    educationKicker: "Base acadêmica",
    education: [
      {
        course: "Tecnólogo em Análise e Desenvolvimento de Sistemas",
        school: "Universidade Tecnológica Federal do Paraná (UTFPR)",
        place: "Cornélio Procópio, PR",
        period: "2016 — Presente · 6º semestre",
        status: "Em andamento",
      },
    ],
    languages: [
      { name: "Português", level: "Nativo" },
      { name: "Inglês", level: "Intermediário" },
    ],
    contactTitle: "Vamos conversar",
    contactSub: "Aberto a oportunidades como Desenvolvedor Full Stack. Me mande uma mensagem.",
    contactCta: "Enviar e-mail",
    cvCta: "Baixar CV (PDF)",
    footerNote: "Desenhado e desenvolvido por Kauan Felipe",
    ui: { langLabel: "Idioma", bgLabel: "Fundo", heroLabel: "Hero", aura: "Aura Field", chrome: "Liquid Chrome" },
  };

  const en = {
    lang: "en",
    ...shared,
    role: "Full Stack Developer",
    location: "Cornélio Procópio, Brazil",
    available: "Available for new projects",
    nav: { work: "Experience", skills: "Stack", projects: "Projects", education: "Education", contact: "Contact" },
    hero: {
      eyebrow: "Full Stack Developer · .NET & React",
      headline: "I build reliable systems that keep businesses running.",
      sub: "Back-end in .NET, front-end in React, and end-to-end DevOps — from database to deploy. Focused on clean code, performance, and measurable impact.",
      ctaPrimary: "View experience",
      ctaSecondary: "Download CV",
      stats: [
        { value: "4+", label: "years of experience" },
        { value: "99.9%", label: "production uptime" },
        { value: "1,000+", label: "transactions/mo integrated" },
      ],
      terminalLines: [
        "$ whoami",
        "kauan_felipe — full stack developer",
        "$ stack --primary",
        ".NET 9 · C# · React · SQL Server · Docker",
        "$ status",
        "● available for new challenges",
      ],
    },
    workTitle: "Experience",
    workKicker: "Where I'm making an impact",
    work: [
      {
        company: "Aquativa Golf Resort",
        role: "Full Stack Developer",
        place: "Cornélio Procópio, BR",
        period: "Jan 2025 — Present",
        current: true,
        bullets: [
          "Modernized legacy .NET RESTful APIs, improving response time by 35% and cutting error rates by 25%.",
          "Built end-to-end payment flows with bank integration (Bradesco), processing 1,000+ transactions/mo at 99.5% success.",
          "Integrated TOTVS ERP, automating data sync and reducing manual entry by 80%.",
          "Set up CI/CD with GitHub Actions and Docker, slashing deploys from 2h to 15min.",
        ],
        tags: [".NET", "React", "SQL Server", "Docker", "CI/CD"],
      },
      {
        company: "Bono Energia",
        role: "Systems Analyst (Mid)",
        place: "Londrina, BR",
        period: "Jul 2023 — Dec 2023",
        bullets: [
          "Developed RESTful APIs in .NET Core integrating 5+ internal and external systems.",
          "Implemented security policies reaching 100% compliance with infosec standards.",
          "Optimized 20+ stored procedures, making queries 40% faster.",
        ],
        tags: [".NET Core", "WebService", "SQL", "Scrum"],
      },
      {
        company: "Dribion Software",
        role: "Technical Support",
        place: "Cornélio Procópio, BR",
        period: "Jan 2021 — Apr 2022",
        bullets: [
          "Resolved 200+ technical issues/mo with 95% first-contact resolution.",
          "Trained 50+ clients and 10+ employees, reducing support tickets by 30%.",
          "Managed fiscal document issuing (NFe, NFC, MDFe, CTe) at 100% compliance.",
        ],
        tags: ["SQL Server", "Support", "QA", "Fiscal"],
      },
    ],
    workTitle: "Experience",
    skillsTitle: "Stack & Technologies",
    skillsKicker: "The tools I use every day",
    skillGroups: [
      { label: "Back-end", items: skills.backend },
      { label: "Front-end", items: skills.frontend },
      { label: "Databases", items: skills.data },
      { label: "DevOps", items: skills.devops },
      { label: "Practices", items: skills.practices },
    ],
    projectsTitle: "Featured Projects",
    projectsKicker: "Selected work",
    projectsNote: "// replace these cards with your real projects — name, description, link and screenshot",
    projects: [
      { name: "Project 01", desc: "Describe the problem you solved and the outcome you achieved.", tags: ["React", "API"], slot: "project 01 screenshot" },
      { name: "Project 02", desc: "Describe the problem you solved and the outcome you achieved.", tags: [".NET", "SQL"], slot: "project 02 screenshot" },
      { name: "Project 03", desc: "Describe the problem you solved and the outcome you achieved.", tags: ["Docker", "CI/CD"], slot: "project 03 screenshot" },
    ],
    educationTitle: "Education",
    educationKicker: "Academic background",
    education: [
      {
        course: "Technologist in Systems Analysis and Development",
        school: "Federal University of Technology – Paraná (UTFPR)",
        place: "Cornélio Procópio, PR",
        period: "2016 — Present · 6th semester",
        status: "In progress",
      },
    ],
    languages: [
      { name: "Portuguese", level: "Native" },
      { name: "English", level: "Intermediate" },
    ],
    contactTitle: "Let's talk",
    contactSub: "Open to opportunities as a Full Stack Developer. Drop me a message.",
    contactCta: "Send email",
    cvCta: "Download CV (PDF)",
    footerNote: "Designed and developed by Kauan Felipe",
    ui: { langLabel: "Language", bgLabel: "Background", heroLabel: "Hero", aura: "Aura Field", chrome: "Liquid Chrome" },
  };

  window.PORTFOLIO = { pt, en };
})();
